### ISSUE TITLE
More explanation for the wiki

### ISSUE THREAD

**Issue by UeberallGebannt** [CrucibleMC/NecroTempus#10]
I just read through the wiki and I'm a bit confused about what I can do with the CraftTweaker bossbar support.

What exactly happens when I execute `BossBar.customize`?

**Comment by brunoxkk0** [comment]
With this method, you can add a BossBar customization filter.
When the client is going to render a boss, and it is of the filtered type, it will use the defined style instead of the default one, so you can change the bars for certain types of mobs, different from the default pink one.

**Comment by UeberallGebannt** [comment]
Thanks for the explanation, I'd recommend adding this to the wiki as otherwise people might be confused (as I was).

**Comment by brunoxkk0** [comment]
I added the explanation on the [wiki](https://github.com/CrucibleMC/NecroTempus/wiki/Craft-Tweaker-(Mine-Tweaker)-Support), I think now it is clearer.
