### ISSUE TITLE
Adding a method allows the PlayerList to add a dummy player name.

### ISSUE THREAD

**Issue by FnTlv** [CrucibleMC/NecroTempus#11]
Adding a method allows the PlayerList to add a dummy player name.
I gave up using bungeecord and velocity because they don't fully support all mods, I have implemented chat sync between multiple servers, playerInv and mod data sync, but PlayerList sync is not possible due to technical limitations, so can you add this feature, appreciate it if you can! This would be great for people who can't use proxies!

**Comment by brunoxkk0** [comment]
I think this is already possible through the PlayerTabManager API

**Comment by brunoxkk0** [comment]
with this method `PlayerTabManager.commonInstance().set(<players>, playerTab)`
over [this class](https://github.com/CrucibleMC/NecroTempus/blob/master/src/main/java/io/github/cruciblemc/necrotempus/api/playertab/PlayerTabManager.java).

**Comment by FnTlv** [comment]
Can you modify CrucibleAPI, add a method `Bukkit.getPlayerTab.addTabCell(String name),` so that the plugin can be, do not need to write mods!

**Comment by EverNife** [comment]
> Can you modify CrucibleAPI, add a method `Bukkit.getPlayerTab.addTabCell(String name),` so that the plugin can be, do not need to write mods!

**I agree a Bukkit bridge for the api would be really good.**


But i think you are missing the complexity of tabbing here.

Each player receives a different TAB.
So, the correct thing is for the plugin that is edditing the tab to manage the groups of players that will receive these custom tabs.

**Comment by EverNife** [comment]
Can you share this code of yours? 
Also, i think its best to open a new issue related to your problem!

You can also ask directly on our discord, might be faster to talk about this :D
