### ISSUE TITLE
Can the PlayerTab skin fallback system be compatible with SimpleSkinBackport？

### ISSUE THREAD

**Issue by Omgise** [CrucibleMC/NecroTempus#13]
SimpleSkinBackport：https://github.com/Roadhog360/SimpleSkinBackport

**Comment by brunoxkk0** [comment]
I believe it is possible, I will study it and, if it is likely, I will try to implement it.

**Comment by Roadhog360** [comment]
Can you show how it's not working? More information than the bare minimum would be nice.

SimpleSkinBackport shouldn't break something like this, this might be on my end to fix. Can you show how it's not working?

@brunoxkk0 Can you show the snippet of source code responsible for the player tab skins? It'd help determine whose fault this issue is

**Comment by Omgise** [comment]
> Can you show how it's not working? More information than the bare minimum would be nice.
> 
> SimpleSkinBackport shouldn't break something like this, this might be on my end to fix. Can you show how it's not working?
> 
> @brunoxkk0 Can you show the snippet of source code responsible for the player tab skins? It'd help determine whose fault this issue is

![屏幕截图 2024-09-21 140116](https://github.com/user-attachments/assets/183b1baf-901e-4f85-901f-7360d047cf14)

**Comment by Roadhog360** [comment]
Issue was likely due to using offline mode. Does it work when using online mode?

**Comment by Omgise** [comment]
effective
![屏幕截图 2024-09-21 191439](https://github.com/user-attachments/assets/0466c684-7989-432c-bfd2-8a8fc7c1f5c0)

**Comment by Roadhog360** [comment]
Vanilla issue then, I don't believe this to be a NecroTempus issue

**Comment by Omgise** [comment]
Maybe I should close the question

**Comment by brunoxkk0** [comment]
I will keep it open to implement compatibility with SimpleSkinBackport, it is interesting to add this support.

**Comment by Roadhog360** [comment]
This issue has nothing to do with SimpleSkinBackport, the issue was caused due to them being in offline mode. The user didn't actually test before reporting skin issues to either of our repos.

**Comment by brunoxkk0** [comment]
I see, in this case, the mod does not fix the skin in offline mode but rather forces the new model to be used.
There is no need to add any support then.
