### ISSUE TITLE
BossBar

### ISSUE THREAD

**Issue by brunoxkk0** [CrucibleMC/NecroTempus#8]
## Custom BossBar
 - [X] supports default colors and lazy ones.
 - [x] added mods compatibility. ~WIP~
 - [x] Bukkit ready API support.
 - [X] Vanilla bosses compatibility.

Vanilla bosses
![Image](https://user-images.githubusercontent.com/26889025/244256661-201dfdbd-481d-40e4-8e27-a24b29b644ee.png)

Botania BossBar compatibility
![Image](https://user-images.githubusercontent.com/26889025/244256297-b5137c9a-c0af-4098-8154-804b0178104e.png)

Custom colored bossbar
![Image](https://user-images.githubusercontent.com/26889025/244257471-759226a8-c5f5-4c9e-822f-46483b365cea.png)

CustomNpcs compatibility
![Image](https://github.com/CrucibleMC/NecroTempus/assets/26889025/37b7e8f4-1c47-4f7e-bf92-37b5d89aee66)
![Image](https://github.com/CrucibleMC/NecroTempus/assets/26889025/b45c55f4-2cd7-4eae-bd40-62c6add58a21)

**Comment by brunoxkk0** [comment]
I believe that there is still work to be done, but I will currently mark it as resolved.

**Comment by Akashiic** [comment]
Tá ficando top dms
